exclude: ['public', 'bin', 'vendor', 'Gemfile', 'Gemfile.lock', 'Procfile', 'Rakefile', 'unicorn.rb', 'config.ru', 'README.md']
destination: 'public'
sass:
    syntax: scss
    style: compressed
prod_guest_form_url: http://api.bethandtyler.com/guest
dev_guest_form_url: http://localhost:5000/guest